services:
  - type: web
    name: earthquake-bot
    env: node
    buildCommand: pnpm install
    startCommand: node index.js
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false 